// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxwOhWH7O3Q2rc3DNgBT4rX5xDS8-KOrA',
    appId: '1:366386022105:web:5fa9d8a14eee0ffb6ca0c8',
    messagingSenderId: '366386022105',
    projectId: 'kismetlyfal',
    authDomain: 'kismetlyfal.firebaseapp.com',
    storageBucket: 'kismetlyfal.firebasestorage.app',
    measurementId: 'G-2GZNE27RTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr-idhj1t5JWYgdTcFhvhmOXSi5G0xpZw',
    appId: '1:366386022105:android:3bd5ae95b1d4977e6ca0c8',
    messagingSenderId: '366386022105',
    projectId: 'kismetlyfal',
    storageBucket: 'kismetlyfal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8X1IgaL4DuIBD-kIm0gv6GsL_Qp0BHhI',
    appId: '1:366386022105:ios:ca00e64df98be4406ca0c8',
    messagingSenderId: '366386022105',
    projectId: 'kismetlyfal',
    storageBucket: 'kismetlyfal.firebasestorage.app',
    androidClientId:
        '366386022105-8u0d81a6s68992v3tpv0af71bc5cgvkm.apps.googleusercontent.com',
    iosClientId:
        '366386022105-7eh5i18jip13ggtecb7gtbpahjbo6c50.apps.googleusercontent.com',
    iosBundleId: 'com.example.kismetly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8X1IgaL4DuIBD-kIm0gv6GsL_Qp0BHhI',
    appId: '1:366386022105:ios:ca00e64df98be4406ca0c8',
    messagingSenderId: '366386022105',
    projectId: 'kismetlyfal',
    storageBucket: 'kismetlyfal.firebasestorage.app',
    androidClientId:
        '366386022105-8u0d81a6s68992v3tpv0af71bc5cgvkm.apps.googleusercontent.com',
    iosClientId:
        '366386022105-7eh5i18jip13ggtecb7gtbpahjbo6c50.apps.googleusercontent.com',
    iosBundleId: 'com.example.kismetly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxwOhWH7O3Q2rc3DNgBT4rX5xDS8-KOrA',
    appId: '1:366386022105:web:d1b60148bad63edc6ca0c8',
    messagingSenderId: '366386022105',
    projectId: 'kismetlyfal',
    authDomain: 'kismetlyfal.firebaseapp.com',
    storageBucket: 'kismetlyfal.firebasestorage.app',
    measurementId: 'G-MN6PGHKE5G',
  );
}
